### ISSUE TITLE
Is it possible to improve the message when no course is found?

### ISSUE THREAD

**Issue by williambelle** [epflgraph/graphsearch_widgets#2]
Hi @tvanbeek, I came across courses in Edu that are probably not indexed in Graph Search. The widget shows "Request failed with status code 500" but the response message is "No Course found". Is it possible to improve the message returned to the user?

For example:

- https://edu.epfl.ch/studyplan/en/doctoral_school/architecture-and-sciences-of-the-city/coursebook/harmony-and-conflicts-AR-678

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <graph-widget-course-courses id="AR-678" locale="en">
    </graph-widget-course-courses>
    <script src="https://cdn.jsdelivr.net/gh/epflgraph/graphsearch_widgets@v1.0.0-alpha.7/dist/index.js"></script>
</body>
</html>

```

![Screenshot from 2024-02-08 16-40-11](https://github.com/epflgraph/graphsearch_widgets/assets/2843501/56bfa4bc-0ec2-4f1d-b005-a719f6bd3f65)

**Comment by tvanbeek** [comment]
Again thanks!

I took a different approach, I hide the component on error (but instead write to console just in case).

1. Otherwise there will be a floating error message, for example "Course not found", somewhere on your page which is irrelevant and difficult to understand for the user
2. Not all errors are predictable
3. Errors are difficult to translate to French

So either the component successfully fetches data and display the result(s), or will render an empty div.

Let me know what you think or if you find something else. Your help is very much appreciated!
